* Agenda: Oct 25, 2017 Hackathon 


** Browsing Loses Aural CSS 

When browsing a math expression, subsequent auditory output appears to
have no Aural CSS.
 
Repro Steps:

Enter  a math expression, 
: \frac{a+b}{c+d}

Notice that the auditory output uses ACSS to audio-format
subexpressions.  Press down-arrow to move down a level, and the
formatting is lost. 

We should retain the original formatting so that the user gets an
implicit cue as to where in the tree he is at any given point.

** Tune Aural CSS Settings 

Need to start tuning  Aural CSS parameters  --- I still dont know
where in the code I make changes.

** Design Thoughts 

Use abstract dimensions for maths: subscripting/superscripting,
nesting, stacking.

In a separate JS file, specify a vector of ACSS tupples for each of
these dimensions:
: (average-pitch, pitch-range, richness, smoothness)

So the vector of tupples might look like:
:[(1 1 0 0) (1 3 0 0)...]

Then the rendering code in the SRE can just apply values from this
vector of tupples during rendering.
